let
    Source = data,
    #"Removed Columns" = Table.RemoveColumns(Source,{"Fixed Location", "LocationOn", "surveytype", "AppTime", "enumerator", "start", "end", "deviceid", "device_info", "text_audit", "today", "loc_1", "loc_2", "loc_3", "loc_4", "sampling_source", "sampling_source_text", "referral_depth", "consent", "gender", "nationality", "nationality_text", "age", "displaced", "n_displaced", "date_first_displaced", "governorate_displaced", "changed_location", "reason_change_location", "reason_change_location_rent", "reason_change_location_tensions", "reason_change_location_better_location", "reason_change_location_went_back", "reason_change_location_unsafe", "reason_change_location_other", "reason_change_location_99", "reason_change_location_text", "disability_level", "gps-Latitude", "gps-Longitude", "gps-Altitude", "gps-Accuracy", "registration", "registration_text", "reason_not_registered", "reason_not_registered_dont_know_how", "reason_not_registered_dont_need", "reason_not_registered_privacy", "reason_not_registered_no_trust", "reason_not_registered_no_result", "reason_not_registered_tried_failed", "reason_not_registered_other", "reason_not_registered_99", "reason_not_registered_text", "live_with", "live_with_text", "living_situation", "living_situation_text", "current_priorities", "current_priorities_healthcare", "current_priorities_cash", "current_priorities_education", "current_priorities_electricity", "current_priorities_employment", "current_priorities_food", "current_priorities_housing", "current_priorities_mental_health", "current_priorities_safety", "current_priorities_return", "current_priorities_sanitation", "current_priorities_other", "current_priorities_98", "current_priorities_99", "current_priorities_text", "perception_coping", "coping_strategies", "coping_strategies_no_unmet", "coping_strategies_community_help", "coping_strategies_diaspora_help", "coping_strategies_skip_meals", "coping_strategies_sold_belongings", "coping_strategies_moved_employment", "coping_strategies_loans_family", "coping_strategies_loans_moneylenders", "coping_strategies_children_school", "coping_strategies_child_labour", "coping_strategies_none", "coping_strategies_other", "coping_strategies_99", "coping_strategies_98", "coping_strategies_text", "perception_incontrol", "in_control_why", "out_control_why", "community_relations", "tension_source", "tension_source_jobs", "tension_source_housing", "tension_source_aid", "tension_source_displaced_host", "tension_source_background", "tension_source_insecurity", "tension_source_lack_comm", "tension_source_solidarity", "tension_source_bonding", "tension_source_leadership", "tension_source_other", "tension_source_98", "tension_source_99", "tension_source_text", "mutual_aid", "mutual_aid_type", "mutual_aid_type_healthcare", "mutual_aid_type_childcare", "mutual_aid_type_food_water", "mutual_aid_type_shelter", "mutual_aid_type_psycho", "mutual_aid_type_electricity", "mutual_aid_type_transport", "mutual_aid_type_info", "mutual_aid_type_acces_aid", "mutual_aid_type_money", "mutual_aid_type_loan", "mutual_aid_type_aid_nfi", "mutual_aid_type_other", "mutual_aid_type_98", "mutual_aid_type_99", "mutual_aid_type_text", "aid_recipient", "aid_type", "aid_type_cash", "aid_type_food", "aid_type_shelter", "aid_type_nfi", "aid_type_water", "aid_type_healthcare", "aid_type_mental_health", "aid_type_education", "aid_type_adult_edu", "aid_type_livelihood", "aid_type_legal", "aid_type_other", "aid_type_98", "aid_type_99", "aid_type_text", "aid_who", "aid_who_text", "perception_coverneeds", "trust_natl_ngo", "trust_civil_soc", "trust_intl_ngo", "trust_un", "trust_red_cross", "trust_govt", "trust_local_auth", "trust_religion", "trust_community_leaders", "trust_factors", "trust_factors_direct_exp", "trust_factors_word_of_mouth", "trust_factors_transparency", "trust_factors_reach", "trust_factors_dignity", "trust_factors_independence", "trust_factors_cultural", "trust_factors_corruption", "trust_factors_media", "trust_factors_other", "trust_factors_99", "trust_factors_text", "perception_consult", "perception_involve", "perception_reach", "perception_dignity", "perception_local_power", "perception_transparenvy", "perception_communicate", "perception_feedback", "perception_action", "expect_consult", "expect_involve", "expect_reach", "expect_dignity", "expect_local_power", "expect_transparenvy", "expect_communicate", "expect_feedback", "expect_action", "info_how", "info_how_face_to_face", "info_how_social_media", "info_how_messaging", "info_how_posters", "info_how_sms", "info_how_community_meetings", "info_how_radio_tv", "info_how_other", "info_how_98", "info_how_99", "info_how_telephone", "info_how_text", "info_source_text", "contradictory_info", "contradictory_info_detail", "info_knowwhere", "want_know_more", "want_know_more_eligibility", "want_know_more_frequency", "want_know_more_types", "want_know_more_schedule", "want_know_more_other", "want_know_more_98", "want_know_more_99", "want_know_more_text", "info_barriers", "info_barriers_disinformation", "info_barriers_social_cohesion", "info_barriers_networks", "info_barriers_movement_restrictions", "info_barriers_no_idea_where", "info_barriers_trust", "info_barriers_no_systematic", "info_barriers_not_accessible_form", "info_barriers_other", "info_barriers_none", "info_barriers_98", "info_barriers_99", "info_barriers_text", "info_source_aid", "info_source_aid_face_to_face", "info_source_aid_social_media", "info_source_aid_messaging", "info_source_aid_telephone", "info_source_aid_posters", "info_source_aid_sms", "info_source_aid_community_meetings", "info_source_aid_radio_tv", "info_source_aid_other", "info_source_aid_98", "info_source_aid_99", "info_source_aid_text", "info_pref_from", "info_pref_from_local_volunteers", "info_pref_from_local_org_staff", "info_pref_from_intl_org_staff", "info_pref_from_govt", "info_pref_from_religious_leaders", "info_pref_from_neighbours", "info_pref_from_friends_family", "info_pref_from_other", "info_pref_from_98", "info_pref_from_99", "info_pref_from_text", "main_fears", "main_fears_physical_safety", "main_fears_losing_loved_one", "main_fears_losing_homeland", "main_fears_cant_return", "main_fears_lost_prospects", "main_fears_no_recovery", "main_fears_identity", "main_fears_no_accountability", "main_fears_community_relations", "main_fears_aid_dependence", "main_fears_social_fabric", "main_fears_other", "main_fears_98", "main_fears_99", "main_fears_text", "confidence_recovery", "plans", "plans_stay_wait", "plans_return_home", "plans_relocate_lb", "plans_leave_temp", "plans_leave_perm", "plans_rebuild", "plans_income", "plans_community_engage", "plans_education_resume", "plans_other", "plans_98", "plans_99", "plans_text", "recovery_actions", "recovery_actions_financial", "recovery_actions_reach_all", "recovery_actions_rebuild", "recovery_actions_livelihood", "recovery_actions_accountability", "recovery_actions_local_power", "recovery_actions_safety", "recovery_actions_political", "recovery_actions_comm_engagement", "recovery_actions_other", "recovery_actions_98", "recovery_actions_99", "recovery_actions_text", "hope_future", "hope_future_text", "message_to_world", "anything_else", "survey", "survey_whynot", "survey_whynot_too_long", "survey_whynot_understanding", "survey_whynot_topic", "survey_whynot_useless", "survey_whynot_too_often", "survey_whynot_relevance", "survey_whynot_other", "survey_whynot_98", "survey_whynot_99", "survey_whynot_text", "phone", "issue", "referral", "enumerator_notes"}),
    #"Sorted Rows" = Table.Sort(#"Removed Columns",{{"SubmissionDate", Order.Descending}}),
    #"Removed groups start end date" = Table.RemoveColumns(#"Sorted Rows",{"start_demo", "end_demo", "start_group_priorities", "end_group_priorities", "start_group_mutualaid", "end_group_mutualaid", "start_group_accesstrust", "end_group_accesstrust", "start_group_expectations", "end_group_expectations", "start_group_info", "end_group_info", "start_group_future", "end_group_future", "formdef_version", "KEY", "isValidated", "group_mutualaid[1]/mutual_aid_health", "group_mutualaid[1]/mutual_aid_childcare", "group_mutualaid[1]/mutual_aid_foodwater", "group_mutualaid[1]/mutual_aid_shelter", "group_mutualaid[1]/mutual_aid_psycho", "group_mutualaid[1]/mutual_aid_elec", "group_mutualaid[1]/mutual_aid_transport", "group_mutualaid[1]/mutual_aid_info", "group_mutualaid[1]/mutual_aid_accessaid", "group_mutualaid[1]/mutual_aid_money", "group_mutualaid[1]/mutual_aid_loan", "group_mutualaid[1]/mutual_aid_nfi", "group_info[1]/trust_info_social_media", "group_info[1]/trust_info_messaging", "group_info[1]/trust_info_radio_tv", "group_info[1]/trust_info_friends_family", "group_info[1]/trust_info_local_ngo", "group_info[1]/trust_info_ingo", "group_info[1]/trust_info_govt", "group_info[1]/info_pref_channel", "audio_audit", "group_info[1]/info_pref_channel_text", "start_demo_sec", "start_prio", "start_mutualaid", "start_accesstrust", "start_expectations", "start_info", "start_future", "end_demo_sec", "end_prio", "end_mutualaid", "end_accesstrust", "end_expectations", "end_info", "end_future"}),
    #"Added Custom" = Table.AddColumn(#"Removed groups start end date", "Full Time All Sections", each [time_demo]+[time_main]),
    #"Added Custom1" = Table.AddColumn(#"Added Custom", "TimeApp minus TimeMain", each [apptimemint]-[Full Time All Sections]),
    #"Added Custom2" = Table.AddColumn(#"Added Custom1", "GAP", each if [TimeApp minus TimeMain] > 20 then "App left open / long pause" else "OK"),
    #"Added Custom3" = Table.AddColumn(#"Added Custom2", "time range accepted", each if [Full Time All Sections] < 19 then "Below 19 mins" else "OK")
in
    #"Added Custom3"